export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';

export const USERNAME_TAKEN = 'USERNAME_TAKEN';
export const ACCOUNT_EXIST = 'ACCOUNT_EXIST';
export const USERNAME_EMAIL_INVALID = 'USERNAME_EMAIL_INVALID';
export const PASSWORD_INVALID = 'PASSWORD_INVALID';
export const CHECK_CONFIRM_EMAIL = 'CHECK_CONFIRM_EMAIL';
export const ACCOUNT_CREATED_SUCCESS = 'ACCOUNT_CREATED_SUCCESS';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

export const AUTHORIZATION_MISSING = 'AUTHORIZATION_MISSING';
export const TOKEN_INVALID_EXPIRED = 'TOKEN_INVALID_EXPIRED';
export const LOGIN_REQUIRED = 'LOGIN_REQUIRED';
export const ADMIN_FORBIDDEN = 'ADMIN_FORBIDDEN';
export const SUPER_ADMIN_FORBIDDEN = 'SUPER_ADMIN_FORBIDDEN';
export const USER_FORBIDDEN = 'USER_FORBIDDEN';

export const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';

export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const VIDEO_CREATED_SUCCESS = 'VIDEO_CREATED_SUCCESS';
export const VIDEO_UPDATED_SUCCESS = 'VIDEO_UPDATED_SUCCESS';
export const VIDEO_NOT_FOUND = 'VIDEO_NOT_FOUND';
export const VIDEO_ALREADY_INACTIVE = 'VIDEO_ALREADY_INACTIVE';
export const VIDEO_ALREADY_ACTIVE = 'VIDEO_ALREADY_ACTIVE';
export const VIDEO_APPROVED_SUCCESS = 'VIDEO_APPROVED_SUCCESS';
export const VIDEO_DELETED_SUCCESS = 'VIDEO_DELETED_SUCCESS';

export const ARTICLE_CREATED_SUCCESS = 'ARTICLE_CREATED_SUCCESS';
export const ARTICLE_EXIST = 'ARTICLE_EXIST';
export const ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND';
export const ARTICLE_UPDATED_SUCCESS = 'ARTICLE_UPDATED_SUCCESS';
export const ARTICLE_ALREADY_ACTIVE = 'ARTICLE_ALREADY_ACTIVE';
export const ARTICLE_APPROVED_SUCCESS = 'ARTICLE_APPROVED_SUCCESS';
export const ARTICLE_ALREADY_INACTIVE = 'ARTICLE_ALREADY_INACTIVE';
export const ARTICLE_DELETED_SUCCESS = 'ARTICLE_DELETED_SUCCESS';

export const ARTICLE_LIKED_SUCCESS = 'ARTICLE_LIKED_SUCCESS';
export const ARTICLE_UNLIKED_SUCCESS = 'ARTICLE_UNLIKED_SUCCESS';
export const ARTICLE_NOT_LIKED = 'ARTICLE_NOT_LIKED';
export const ARTICLE_ALREADY_LIKED = 'ARTICLE_ALREADY_LIKED';

export const COMMENT_CREATED_SUCCESS = 'COMMENT_CREATED_SUCCESS';
export const COMMENT_DELETED_SUCCESS = 'COMMENT_DELETED_SUCCESS';
export const COMMENT_UPDATED_SUCCESS = 'COMMENT_UPDATED_SUCCESS';
export const COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND';
export const COMMENT_NOT_OWNER = 'COMMENT_NOT_OWNER';

export const VIDEO_RATE_UPDATED_SUCCESS = 'VIDEO_RATE_UPDATED_SUCCESS';
export const VIDEO_RATE_CREATED_SUCCESS = 'VIDEO_RATE_CREATED_SUCCESS';

export const VIDEO_SHARED_SUCCESS = 'VIDEO_SHARED_SUCCESS';
