export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';

export const USERNAME_TAKEN = 'USERNAME_TAKEN';
export const EMAIL_TAKEN = 'EMAIL_TAKEN';
export const PHONE_NUMBER_TAKEN = 'PHONE_NUMBER_TAKEN';
export const USERNAME_EMAIL_INVALID = 'USERNAME_EMAIL_INVALID';
export const PASSWORD_INVALID = 'PASSWORD_INVALID';
export const PASSWORD_REQUIRED = 'PASSWORD_REQUIRED';
export const OLD_PASSWORD_INVALID = 'OLD_PASSWORD_INVALID';
export const NEW_PASSWORD_SAME_AS_OLD = 'NEW_PASSWORD_SAME_AS_OLD';
export const CHECK_CONFIRM_EMAIL = 'CHECK_CONFIRM_EMAIL';
export const ACCOUNT_CREATED_SUCCESS = 'ACCOUNT_CREATED_SUCCESS';
export const ACCOUNT_UPDATED_SUCCESS = 'ACCOUNT_UPDATED_SUCCESS';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const PASSWORD_CHANGED_SUCCESS = 'PASSWORD_CHANGED_SUCCESS';
export const AVATAR_UPDATED_SUCCESS = 'AVATAR_UPDATED_SUCCESS';

export const AUTHORIZATION_MISSING = 'AUTHORIZATION_MISSING';
export const TOKEN_INVALID_EXPIRED = 'TOKEN_INVALID_EXPIRED';
export const LOGIN_REQUIRED = 'LOGIN_REQUIRED';
export const ADMIN_FORBIDDEN = 'ADMIN_FORBIDDEN';
export const SUPER_ADMIN_FORBIDDEN = 'SUPER_ADMIN_FORBIDDEN';
export const USER_FORBIDDEN = 'USER_FORBIDDEN';
export const USER_BLOCKED = 'USER_BLOCKED';
export const USER_ALREADY_BLOCKED = 'USER_ALREADY_BLOCKED';
export const USER_ALREADY_ACTIVE = 'USER_ALREADY_ACTIVE';
export const USER_BLOCKED_SUCCESS = 'USER_BLOCKED_SUCCESS';
export const USER_UNBLOCKED_SUCCESS = 'USER_UNBLOCKED_SUCCESS';
export const USER_DELETED_SUCCESS = 'USER_DELETED_SUCCESS';
export const OTP_VERIFIED_SUCCESS = 'OTP_VERIFIED_SUCCESS';
export const OTP_ALREADY_VERIFIED = 'OTP_ALREADY_VERIFIED';
export const OTP_INCORRECT = 'OTP_INCORRECT';
export const OTP_RESEND_SUCCESS = 'OTP_RESEND_SUCCESS';

export const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';

export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const VIDEO_EXIST = 'VIDEO_EXIST';
export const VIDEO_CREATED_SUCCESS = 'VIDEO_CREATED_SUCCESS';
export const VIDEO_UPDATED_SUCCESS = 'VIDEO_UPDATED_SUCCESS';
export const VIDEO_NOT_FOUND = 'VIDEO_NOT_FOUND';
export const VIDEO_TAGS_NOT_FOUND = 'VIDEO_TAGS_NOT_FOUND';
export const VIDEO_ALREADY_INACTIVE = 'VIDEO_ALREADY_INACTIVE';
export const VIDEO_ALREADY_ACTIVE = 'VIDEO_ALREADY_ACTIVE';
export const VIDEO_APPROVED_SUCCESS = 'VIDEO_APPROVED_SUCCESS';
export const VIDEO_DISABLED_SUCCESS = 'VIDEO_DISABLED_SUCCESS';
export const VIDEO_DELETED_SUCCESS = 'VIDEO_DELETED_SUCCESS';

export const ARTICLE_EXIST = 'ARTICLE_EXIST';
export const ARTICLE_CREATED_SUCCESS = 'ARTICLE_CREATED_SUCCESS';
export const ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND';
export const ARTICLE_TAGS_NOT_FOUND = 'ARTICLE_TAGS_NOT_FOUND';
export const ARTICLE_UPDATED_SUCCESS = 'ARTICLE_UPDATED_SUCCESS';
export const ARTICLE_ALREADY_ACTIVE = 'ARTICLE_ALREADY_ACTIVE';
export const ARTICLE_APPROVED_SUCCESS = 'ARTICLE_APPROVED_SUCCESS';
export const ARTICLE_ALREADY_INACTIVE = 'ARTICLE_ALREADY_INACTIVE';
export const ARTICLE_DISABLED_SUCCESS = 'ARTICLE_DISABLED_SUCCESS';
export const ARTICLE_DELETED_SUCCESS = 'ARTICLE_DELETED_SUCCESS';
export const ARTICLE_FEATURED_SUCCESS = 'ARTICLE_FEATURED_SUCCESS';
export const ARTICLE_UNFEATURED_SUCCESS = 'ARTICLE_UNFEATURED_SUCCESS';
export const ARTICLE_ALREADY_FEATURED = 'ARTICLE_ALREADY_FEATURED';
export const ARTICLE_ALREADY_UNFEATURED = 'ARTICLE_ALREADY_UNFEATURED';

export const ARTICLE_LIKED_SUCCESS = 'ARTICLE_LIKED_SUCCESS';
export const ARTICLE_UNLIKED_SUCCESS = 'ARTICLE_UNLIKED_SUCCESS';
export const ARTICLE_NOT_LIKED = 'ARTICLE_NOT_LIKED';
export const ARTICLE_ALREADY_LIKED = 'ARTICLE_ALREADY_LIKED';

export const ARTICLE_BOOKMARKED_SUCCESS = 'ARTICLE_BOOKMARKED_SUCCESS';
export const ARTICLE_UNBOOKMARKED_SUCCESS = 'ARTICLE_UNBOOKMARKED_SUCCESS';
export const ARTICLE_NOT_BOOKMARKED = 'ARTICLE_NOT_BOOKMARKED';
export const ARTICLE_ALREADY_BOOKMARKED = 'ARTICLE_ALREADY_BOOKMARKED';

export const COMMENT_CREATED_SUCCESS = 'COMMENT_CREATED_SUCCESS';
export const COMMENT_DELETED_SUCCESS = 'COMMENT_DELETED_SUCCESS';
export const COMMENT_UPDATED_SUCCESS = 'COMMENT_UPDATED_SUCCESS';
export const COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND';
export const COMMENT_NOT_OWNER = 'COMMENT_NOT_OWNER';

export const VIDEO_RATE_UPDATED_SUCCESS = 'VIDEO_RATE_UPDATED_SUCCESS';
export const VIDEO_RATE_CREATED_SUCCESS = 'VIDEO_RATE_CREATED_SUCCESS';

export const VIDEO_SHARED_SUCCESS = 'VIDEO_SHARED_SUCCESS';

export const DASHBOARD_OVERVIEW_SUCCESS = 'DASHBOARD_OVERVIEW_SUCCESS';

export const PLAN_TAKEN = 'PLAN_TAKEN';
export const PLAN_NOT_FOUND = 'PLAN_NOT_FOUND';
export const ADS_NOT_FOUND = 'ADS_NOT_FOUND';
export const STORY_NOT_FOUND = 'STORY_NOT_FOUND';
export const ADS_PLAN_CREATED_SUCCESS = 'ADS_PLAN_CREATED_SUCCESS';
export const ADS_PLAN_UPDATED_SUCCESS = 'ADS_PLAN_UPDATED_SUCCESS';
export const STORY_PLAN_CREATED_SUCCESS = 'STORY_PLAN_CREATED_SUCCESS';
export const STORY_PLAN_UPDATED_SUCCESS = 'STORY_PLAN_UPDATED_SUCCESS';
export const ADS_CREATED_SUCCESS = 'ADS_CREATED_SUCCESS';
export const ADS_UPDATED_SUCCESS = 'ADS_UPDATED_SUCCESS';
export const STORY_CREATED_SUCCESS = 'STORY_CREATED_SUCCESS';
export const STORY_UPDATED_SUCCESS = 'STORY_UPDATED_SUCCESS';
export const ADS_DELETED_SUCCESS = 'ADS_DELETED_SUCCESS';
export const STORY_DELETED_SUCCESS = 'STORY_DELETED_SUCCESS';
export const ADS_DISABLED_SUCCESS = 'ADS_DISABLED_SUCCESS';
export const STORY_DISABLED_SUCCESS = 'STORY_DISABLED_SUCCESS';
export const ADS_ACTIVATED_SUCCESS = 'ADS_ACTIVATED_SUCCESS';
export const STORY_ACTIVATED_SUCCESS = 'STORY_ACTIVATED_SUCCESS';
export const ADS_ALREADY_INACTIVE = 'ADS_ALREADY_INACTIVE';
export const ADS_ALREADY_ACTIVE = 'ADS_ALREADY_ACTIVE';
export const STORY_ALREADY_INACTIVE = 'STORY_ALREADY_INACTIVE';
export const STORY_ALREADY_ACTIVE = 'STORY_ALREADY_ACTIVE';

export const PLAYLIST_NOT_FOUND = 'PLAYLIST_NOT_FOUND';
export const PLAYLIST_UPDATED_SUCCESS = 'PLAYLIST_UPDATED_SUCCESS';
export const PLAYLIST_CREATED_SUCCESS = 'PLAYLIST_CREATED_SUCCESS';
export const PLAYLIST_DELETED_SUCCESS = 'PLAYLIST_DELETED_SUCCESS';
export const VIDEO_ADDED_TO_PLAYLIST__SUCCESS = 'VIDEO_ADDED_TO_PLAYLIST__SUCCESS';
export const VIDEO_REMOVED_FROM_PLAYLIST_SUCCESS = 'VIDEO_REMOVED_FROM_PLAYLIST_SUCCESS';
