export const IMAGES_URL = process.env.NEXT_PUBLIC_IMAGES_URL;

export const STAGING_URL = process.env.NEXT_PUBLIC_FRONTEND_STAGING_URL;
export const PROD_URL = process.env.NEXT_PUBLIC_FRONTEND_PRODUCTION_URL;
export const DEV_URL = process.env.NEXT_PUBLIC_FRONTEND_DEVELOPMENT_URL;
